---
- name: Add key
  apt_key: url="http://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present 
  become: yes

- name: Add repo
  apt_repository: repo='deb http://deb.nodesource.com/node_{{ node_version }} {{ distro }} main'  update_cache=yes
  become: yes

- name: Install nodejs
  apt: name="{{ item }}" state=latest
  become: yes
  with_items:
  - npm

- name: Ensure n is present
  npm:
    state: present
    name: n
    global: yes

- name: n version
  shell: "n {{ n_node_version }}"

- name : Install latest npm
  npm:  name="{{ item.name }}" global="{{ item.global }}" state="{{ item.state }}"
  with_items: "{{ node_modules }}"
  when: node_modules|length > 0
  become: yes
