---
- name: Ensure apt-transport-https is installed.
  apt: name=apt-transport-https state=present
  become: yes

- name: Add Nodesource apt key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present
  become: yes

- name: Add NodeSource repositories for Node.js.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ n_node_version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ n_node_version }} {{ ansible_distribution_release }} main"
  register: node_repo
  become: yes

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: node_repo.changed
  become: yes

- name: Ensure Node.js and npm are installed.
  apt: "name=nodejs={{ n_node_version|regex_replace('x', '') }}* state=present"
  become: yes

- name: Define nodejs_install_npm_user
  set_fact:
  nodejs_install_npm_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"

- name: Create npm global directory
  file:
    path: "{{ npm_config_prefix }}"
    owner: "{{ nodejs_install_npm_user }}"
    group: "{{ nodejs_install_npm_user }}"
    state: directory

- name: Add npm_config_prefix bin directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- name: Ensure npm global packages are installed.
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: "{{ item.global | default('yes') }}"
    state: "{{ item.state | default('present') }}"
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_config_prefix }}"
    NODE_PATH: "{{ npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{ npm_config_unsafe_perm }}"
  with_items: "{{ node_modules }}"
  become: yes
  when: node_modules|length > 0

- name: Install packages defined in a given package.json.
  npm:
    path: "{{ nodejs_package_json_path }}"
  when: nodejs_package_json_path is defined and nodejs_package_json_path
  

