---
- name: Add key
  apt_key: url="http://deb.nodesource.com/gpgkey/nodesource.gpg.key" state=present 

- name: Add repo
  apt_repository: repo='deb http://deb.nodesource.com/node_0.10 trusty main'  update_cache=yes

- name: Install nodejs
  apt: name=nodejs state=latest
  become: yes

- name : Install latest npm
  npm:  name="{{ item.name }}" global="{{ item.global }}" state="{{ item.state }}"
  with_items: "{{ node_modules }}"
  become: yes
